### ISSUE TITLE
Error adding plugin

### ISSUE THREAD

**Issue by GregCornis** [fdncred/nu_plugin_parquet#12]
I tried to install the plugin as the README states, but I have an error : "failed to fill whole buffer".
```shell
$ cargo install nu_plugin_from_parquet
$ register ~/.cargo/bin/nu_plugin_from_parquet
Error:   × Deprecated: register
   ╭─[entry #90:1:1]
 1 │ register ~/.cargo/bin/nu_plugin_from_parquet
   · ────┬───
   ·     ╰── `register` is deprecated and will be removed in 0.94. Please use `plugin add` and `plugin use` instead
   ╰────
  help: for more info: https://www.nushell.sh/book/plugins.html

Error:   × Error getting signatures
   ╭─[entry #90:1:1]
 1 │ register ~/.cargo/bin/nu_plugin_from_parquet
   · ────┬───
   ·     ╰── Plugin failed to load: unable to get encoding from plugin: failed to fill whole buffer
$ plugin add ~/.cargo/bin/nu_plugin_from_parquet
Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: unable to get encoding from plugin: failed to fill whole buffer
```
I'm using nushell 0.93.

Do you have any idea what could cause the issue ?

**Comment by fdncred** [comment]
`register` is being removed. This plugin only supports the latest versions of nushell because I always update them to support the most recent main branch. If you have the latest version of nushell you should do `plugin add ~/path/to/nu_plugin_from_parquet`.

I updated the readme. Thanks.

**Comment by GregCornis** [comment]
Thanks, I thought that too, but I have the same error with `plugin add`
```shell
$ plugin add ~/.cargo/bin/nu_plugin_from_parquet
Error: nu::shell::plugin_failed_to_load

  × Plugin failed to load: unable to get encoding from plugin: failed to fill whole buffer
```

**Comment by fdncred** [comment]
I'm using `from parquet` without issue. I wonder if you're trying to use it with a different version of nushell? It's very important that the plugin match the version of nushell which is 0.95.1. You may be able to get the plugin to compile with 0.95.0 also but you'd have to change the cargo.toml file.

**Comment by GregCornis** [comment]
Yes that could be it, I'm using nushell v0.93. Is there no way to install an older version of the plugin to match an older version of nushell ?
As a side note, [nu's latest release on crates.io is 0.95.0](/Users/chalony/Documents/Code/inspection-monitoring/lambda-missions-json2csv).

**Comment by GregCornis** [comment]
I have checked with nu v0.95.0 with the same error

**Comment by fdncred** [comment]
You cannot run 0.95 plugins with 0.93. You'll need to upgrade to 95.0 or 95.1 and delete your $nu.plugin-path file. Then make sure to compile this plugin against the version of nushell you have. Then you need to plugin add /path/to/nu_plugin_from_parquet and everything should work.

**Comment by GregCornis** [comment]
Alright, it does work thanks 👍 

Note: I tried to make it compatible with 0.93.0 but the plugin wouldn't compile, I imagine some breaking change happened between then and now. I would be nice to have one release per `nushell` release, so that we can install the plugin whatever the version of nushell we use.

Thanks for you help anyway :)

**Comment by fdncred** [comment]
You could just go back in the commits and look for the commit that says something like "make compatible with 0.93.0" and compile this plugin with that as the latest commit. yes, there have been breaking changes between 93 and 95.
