### ISSUE TITLE
nu_plugin_from_parquet fails with nushell 0.74.0

### ISSUE THREAD

**Issue by maxim-uvarov** [fdncred/nu_plugin_parquet#5]
Hello! I wonder if there is a quick way to fix the failing plugin? 

<img width="961" alt="image" src="https://user-images.githubusercontent.com/4896754/211761891-fb110725-407f-4a11-b5f5-d3afbe848948.png">

I tried to build the latest version of the plugin from the repo again, but the result is the same.

**Comment by maxim-uvarov** [comment]
Adding `allows_unknown_args` to the `/Users/user/Library/Application Support/nushell/plugin.nu` seems to did the trick. 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/4896754/211763538-d47761cf-1b60-4ca0-805c-2f280d24626e.png">
Thanks!

**Comment by maxim-uvarov** [comment]
Nope, I should do something different than editing the file
`/Users/user/Library/Application Support/nushell/plugin.nu`

I would be glad to be taught what to do in such cases.

**Comment by maxim-uvarov** [comment]
Ok, seems like I found it. I needed to execute in nushell command once again:
`register ~/.cargo/bin/nu_plugin_from_parquet`

Sorry for bombing issue comments here :(

**Comment by fdncred** [comment]
ya, no worries. the key with plugins is to make sure plugins match the version of nushell. so, i usually change the cargo.toml to match, recompile and install, and re-register them.
