### ISSUE TITLE
Register hangs on nushell 0.77.1

### ISSUE THREAD

**Issue by hoop33** [fdncred/nu_plugin_parquet#7]
I came across this plugin and tried to register. After installation, I ran:

`register ~/.cargo/bin/nu_plugin_from_parquet`

Trying to autocomplete the plugin name hangs. Trying to type the path to the plugin hangs before the final "t".

I cloned the source, bumped the `nu-plugin` and `nu-protocol` crates to "0.77.1" and made a couple code changes:

```
diff --git i/src/main.rs w/src/main.rs
index f93a919..1d36503 100644
--- i/src/main.rs
+++ w/src/main.rs
@@ -54,5 +54,5 @@ impl Plugin for FromParquet {
 }
 
 fn main() {
-    serve_plugin(&mut FromParquet::new(), JsonSerializer);
+    serve_plugin(&mut FromParquet::new(), JsonSerializer {});
 }
```

```
diff --git i/src/from_parquet.rs w/src/from_parquet.rs
index 3359e9e..afb7142 100644
--- i/src/from_parquet.rs
+++ w/src/from_parquet.rs
@@ -29,12 +29,12 @@ fn convert_to_nu(field: &Field, span: Span) -> Value {
             .try_into()
             .map(|l| Value::int(l, span))
             .unwrap_or_else(|e| Value::Error {
-                error: ShellError::CantConvert {
+                error: Box::from(ShellError::CantConvert {
                     to_type: "i64".into(),
                     from_type: "u64".into(),
                     span,
                     help: Some(e.to_string()),
-                },
+                }),
             }),
         Field::Float(f) => Value::float((*f).into(), span),
         Field::Double(f) => Value::float(*f, span),
```

I can open a PR, but not sure about backward compatibility concerns or how close to current nushell you want to stay. Thanks for your work on this -- I'm a nushell noob and this plugin will be helpful!

**Comment by fdncred** [comment]
Hey Thanks for stopping by! I applied your changes and a few more to get it building on the latest nushell main. I was able to get it to compile and open the test file.
![image](https://user-images.githubusercontent.com/343840/228543737-1611dee6-f0b4-4cdf-8c97-dc2628600a19.png)

I just pushed these changes.

**Comment by fdncred** [comment]
Let me know if you still have issues. To compile this version directly from this repo, you'll need to clone the nushell repository at the same level so nushell and nu_plugin_from_parquet are siblings.

**Comment by hoop33** [comment]
Registering hung on the 0.77.1 release version, so as you said I built nushell 0.77.2 from source and then everything worked. Thanks!

**Comment by fdncred** [comment]
I'm definitely open to PRs too, if there are things you'd like to add or change. Good luck!
